POST https://localhost:7068/api/video/getuploadurl HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0NzVGQThDNDdCOTg0QUI2NzZDMDZENUU0OUNERDgxIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2NzYyMjQ2NzUsImV4cCI6MTY3NjIyODI3NSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzA2OCIsImNsaWVudF9pZCI6InRiZGFuY2VkYW5jZWZyb250Iiwic3ViIjoiODE4NzI3IiwiYXV0aF90aW1lIjoxNjc2MjI0Njc0LCJpZHAiOiJsb2NhbCIsImp0aSI6IjQxQzg4RThDNzdGN0I0M0FDNkQ2OTkzMjM1Q0VGNjk1Iiwic2lkIjoiQzEwMjgzNDY3RjZFMEM2RUUzNDEzQ0Y4MzNCMTQ2RDEiLCJpYXQiOjE2NzYyMjQ2NzUsInNjb3BlIjpbIm9wZW5pZCIsInRiZGFuY2VkYW5jZWFwaS5yZWFkIl0sImFtciI6WyJwd2QiXX0.aS_-zQMqHo1-xBFsVGd75QSN1jk3wYNqD9bRZ3AdqNCX62nXFxddKvzQ7L3idco6g1BdCteWKOQxrAFoo4A1zFUznCPkp-SNBRPZgKSxWei6pQmOgXO630a8ukEsMWIiYAXYBRANau6wAQSYqSHo_cmhS96v4E5Bgg4WxdqkoHWYijPDyqbUO7P3SyBf3r0_WMQI3hY8aZENlqiq-as872D7OpQDY2pIQvaO3xJ_RdzybjxGabKU5rHM8mevI1ZS2b5XuUyr7LFJxf93A7TIFqksCnwOdXYgF-AvL1VXiKWn7LC7e1BIpMUiJARf6OXIxocaUjjjYupZGYDZp_JUbg

{"nameOfVideo":"Testabc",
"recorded":"2022-10-09T21:38:02.010Z",
"sharedWith":{"name":"Warsztaty Footworki 2022",
"id":"warsztatyFootworki2022","assignment":3}}