//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface PagedResponseOfVideoInformation {
    items?: VideoInformation[];
    totalCount?: number;
    pageNumber?: number;
    pageSize?: number;
}

export interface VideoInformation {
    videoId?: string;
    blobId?: string;
    name?: string;
    recordedDateTime?: Date;
    duration?: string | undefined;
    converted?: boolean;
    commentVisibility?: number;
    thumbnailUrl?: string | undefined;
    sizeBytes?: number;
    isOwner?: boolean;
}

export interface PagedRequest {
}

export interface ListMyVideosRequest extends PagedRequest {
}

export interface UploadUrlResponse {
    sas?: string;
    videoId?: string;
    expireAt?: Date;
}

export interface ProduceUploadUrlResponse extends UploadUrlResponse {
}

export interface ProduceUploadUrlRequest {
    nameOfVideo: string;
    fileName: string;
    recordedTimeUtc?: Date;
    sharedWith: string;
    sharingWithType?: SharingWithType;
    videoId?: string | undefined;
}

export enum SharingWithType {
    NotSpecified = 0,
    Group = 1,
    Event = 2,
    Private = 3,
}

/** the dto used to send an error response to the client */
export interface ErrorResponse {
    /** the http status code sent to the client. default is 400. */
    statusCode?: number;
    /** the message for the error response */
    message?: string;
    /** the collection of errors for the current context */
    errors?: { [key: string]: string[]; };
}

export interface RefreshUploadUrlResponse extends UploadUrlResponse {
}

export interface RenameVideoRequest {
    newName?: string;
}

export interface UpdateCommentSettingsRequest {
    commentVisibility?: number;
}

export interface VideoInformationResponse {
    videoInformation?: VideoInformation;
}

export interface GetPublishSasResponse {
    sas?: string;
}

export interface GetThumbnailSasResponse {
    sas?: string;
}

export interface PublicConvertedVideoResponse {
    videoId?: string;
}

export interface UpdateVideoInfoRequest {
    videoId: string;
    recordedDateTime: Date;
    duration?: string;
    metadata?: string | undefined;
}

export interface VideoToThumbnailResponse {
    videoExists?: boolean;
    videoToThumbnail?: VideoToThumbnailModel | undefined;
}

export interface VideoToThumbnailModel {
    id?: string;
    blobId?: string;
    fileName?: string;
    sas?: string;
}

export interface VideoToTransformResponse {
    videoExists?: boolean;
    videoToTransform?: VideoToTransformModel | undefined;
}

export interface VideoToTransformModel {
    id?: string;
    fileName?: string;
    sas?: string;
}

export interface AcceptTransferResponse {
    accepted?: boolean;
    requiredBytes?: number | undefined;
    availableBytes?: number | undefined;
    error?: string | undefined;
}

export interface TransferSummaryResponse {
    linkId?: string;
    status?: string;
    createdAt?: Date;
    expireAt?: Date;
    shareUrl?: string;
    totalSizeBytes?: number;
    acceptedByUserId?: string | undefined;
    acceptedAt?: Date | undefined;
    rolledBackAt?: Date | undefined;
    rollbackDeadline?: Date | undefined;
    items?: TransferItemInfo[];
}

export interface TransferItemInfo {
    videoId?: string;
    name?: string;
    recordedDateTime?: Date;
    duration?: string | undefined;
    sizeBytes?: number;
}

export interface CreateTransferRequest {
    expirationDays?: number;
}

export interface TransferInfoResponse {
    linkId?: string;
    status?: string;
    expireAt?: Date;
    totalSizeBytes?: number;
    rollbackDeadline?: Date | undefined;
    items?: TransferItemInfo[];
}

export interface ListMyTransfersResponse {
    transfers?: TransferSummaryResponse[];
}

export interface SharedLinkResponse {
    linkId?: string;
    videoId?: string;
    videoName?: string;
    createdAt?: Date;
    expireAt?: Date;
    isRevoked?: boolean;
    shareUrl?: string;
    allowComments?: boolean;
    allowAnonymousComments?: boolean;
}

export interface CreateSharedLinkRequest {
    expirationDays?: number;
    allowComments?: boolean;
    allowAnonymousComments?: boolean;
}

export interface ListMySharedLinksResponse {
    links?: SharedLinkResponse[];
}

export interface SharedVideoInfoResponse {
    videoId?: string;
    name?: string;
    duration?: string | undefined;
    recordedDateTime?: Date;
    commentVisibility?: number;
    allowCommentsOnThisLink?: boolean;
    allowAnonymousCommentsOnThisLink?: boolean;
}

export interface AddGroupAdminRequest {
    userId?: string;
}

export interface CreateGroupResponse {
    id?: string;
}

export interface CreateGroupRequest {
    name: string;
    seasonStart: Date;
    seasonEnd: Date;
}

export interface ListMyGroupsResponse {
    groups?: GroupModel[];
}

export interface PagedResponseOfVideoFromGroupInformation {
    items?: VideoFromGroupInformation[];
    totalCount?: number;
    pageNumber?: number;
    pageSize?: number;
}

export interface VideoFromGroupInformation extends VideoInformation {
    groupId?: string;
    groupName?: string;
}

export interface ListAllGroupVideosRequest extends PagedRequest {
}

export interface ListGroupAdminsResponse {
    admins?: GroupAdminModel[];
}

export interface GroupAdminModel {
    userId?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
}

export interface ListGroupMembersResponse {
    members?: GroupMemberModel[];
}

export interface GroupMemberModel {
    userId?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    whenJoined?: Date;
}

export interface ListGroupVideosRequest extends PagedRequest {
}

export interface UpdateGroupMemberRequest {
    whenJoined?: Date;
}

export interface CreateNewEventResponse {
    id?: string;
}

export interface CreateNewEventRequest {
    event: EventModel;
}

export interface EventModel {
    id?: string;
    name: string;
    date: Date;
}

export interface ListEventVideosRequest extends PagedRequest {
}

export interface CommentResponse {
    id?: string;
    videoId?: string;
    authorName?: string | undefined;
    postedAsAnonymous?: boolean;
    content?: string;
    createdAt?: Date;
    updatedAt?: Date | undefined;
    isHidden?: boolean | undefined;
    isReported?: boolean | undefined;
    reportedReason?: string | undefined;
    isOwn?: boolean;
    canModerate?: boolean;
}

export interface CreateCommentRequest {
    content?: string;
    anonymousId?: string | undefined;
    authorName?: string | undefined;
}

export interface PagedResponseOfCommentResponse {
    items?: CommentResponse[];
    totalCount?: number;
    pageNumber?: number;
    pageSize?: number;
}

export interface ListCommentsByLinkRequest extends PagedRequest {
}

export interface ListCommentsForVideoRequest extends PagedRequest {
}

export interface ReportCommentRequest {
    reason?: string;
}

export interface UpdateCommentRequest {
    content?: string;
    authorName?: string | undefined;
}

export interface ApproveAccessRequestRequest {
    requestId?: string;
    isGroup?: boolean;
    isApproved?: boolean;
}

export interface ListAccessRequestsResponse {
    accessRequests?: RequestedAccessModel[];
}

export interface RequestedAccessModel {
    name?: string;
    requestorFirstName?: string;
    requestorLastName?: string;
    whenJoined?: Date | undefined;
    requestId?: string;
    isGroup?: boolean;
}

export interface ListAllEventsAndGroupsResponse {
    events?: EventModel[];
    groups?: GroupModel[];
}

export interface GroupModel {
    id?: string;
    name?: string;
    seasonStart?: Date;
    seasonEnd?: Date;
}

export interface GetUserAccessResponse {
    assigned?: GetUserAccessSet;
    available?: GetUserAccessSet;
    pending?: ListUserAccessPending;
    administeredGroupIds?: string[];
}

export interface GetUserAccessSet {
    events?: EventModel[];
    groups?: GroupModel[];
}

export interface ListUserAccessPending {
    events?: string[];
    groups?: string[];
}

export interface RequestAccessRequest {
    events?: string[] | undefined;
    groups?: RequestAccessGroupModel[] | undefined;
}

export interface RequestAccessGroupModel {
    id?: string;
    joinedDate?: Date;
}
