// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TB.DanceDance.Videos.Infrastructure;

#nullable disable

namespace TB.DanceDance.Videos.Infrastructure.Migrations
{
    [DbContext(typeof(VideosDbContext))]
    partial class VideosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TB.DanceDance.Videos.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnonymousName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReported")
                        .HasColumnType("boolean");

                    b.Property<bool>("PostedAsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("ReportedReason")
                        .HasColumnType("text");

                    b.Property<byte[]>("ShaOfAnonymousId")
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("SharedLinkId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SharedLinkId");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoId");

                    b.ToTable("Comments", "comments");
                });

            modelBuilder.Entity("TB.DanceDance.Videos.Domain.Entities.SharedLink", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("AllowAnonymousComments")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowComments")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("SharedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SharedBy");

                    b.HasIndex("VideoId");

                    b.ToTable("SharedLinks", "video");
                });

            modelBuilder.Entity("TB.DanceDance.Videos.Domain.Entities.SharedWith", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoId");

                    b.ToTable("SharedWith", "video");
                });

            modelBuilder.Entity("TB.DanceDance.Videos.Domain.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobId")
                        .HasColumnType("text");

                    b.Property<int>("CommentVisibility")
                        .HasColumnType("integer");

                    b.Property<bool>("Converted")
                        .HasColumnType("boolean");

                    b.Property<long>("ConvertedBlobSize")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedTill")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SharedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceBlobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SourceBlobSize")
                        .HasColumnType("bigint");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Videos", "video");
                });

            modelBuilder.Entity("TB.DanceDance.Videos.Domain.Entities.VideoMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Metadata")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("VideoMetadata", "video");
                });

            modelBuilder.Entity("TB.DanceDance.Videos.Domain.Entities.Comment", b =>
                {
                    b.HasOne("TB.DanceDance.Videos.Domain.Entities.SharedLink", "SharedLink")
                        .WithMany()
                        .HasForeignKey("SharedLinkId");

                    b.HasOne("TB.DanceDance.Videos.Domain.Entities.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SharedLink");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("TB.DanceDance.Videos.Domain.Entities.SharedLink", b =>
                {
                    b.HasOne("TB.DanceDance.Videos.Domain.Entities.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("TB.DanceDance.Videos.Domain.Entities.SharedWith", b =>
                {
                    b.HasOne("TB.DanceDance.Videos.Domain.Entities.Video", "Video")
                        .WithMany("SharedWith")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("TB.DanceDance.Videos.Domain.Entities.VideoMetadata", b =>
                {
                    b.HasOne("TB.DanceDance.Videos.Domain.Entities.Video", null)
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TB.DanceDance.Videos.Domain.Entities.Video", b =>
                {
                    b.Navigation("SharedWith");
                });
#pragma warning restore 612, 618
        }
    }
}
