using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace TB.DanceDance.Videos.Domain.Entities;

public class SharedLink
{
    private SharedLink() { }
    
    public string Id { get; set; } = null!;
    public Guid VideoId { get; set; }
    public string SharedBy { get; set; } = null!;

    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset ExpireAt { get; set; }
    public bool IsRevoked { get; set; } = false;

    /// <summary>
    /// Whether commenting is allowed through this shared link.
    /// </summary>
    public bool AllowComments { get; set; } = true;

    /// <summary>
    /// Whether anonymous (non-logged-in) users can comment through this shared link.
    /// Only applies if AllowComments is true.
    /// </summary>
    public bool AllowAnonymousComments { get; set; } = false;

    public Video Video { get; set; } = null!;

    public class Factory
    {
        /// <summary>
        /// Creates a new, active public sharing link for a video.
        /// </summary>
        public static SharedLink Create(
            string linkId,
            Guid videoId,
            string sharedBy,
            int expirationDays,
            bool allowComments,
            bool allowAnonymousComments)
        {
            var now = DateTimeOffset.UtcNow;
            return new SharedLink()
            {
                Id = linkId,
                VideoId = videoId,
                SharedBy = sharedBy,
                CreatedAt = now,
                ExpireAt = now.AddDays(expirationDays),
                IsRevoked = false,
                AllowComments = allowComments,
                AllowAnonymousComments = allowAnonymousComments
            };
        }
    }
}

public class SharedLinkConfiguration : IEntityTypeConfiguration<SharedLink>
{
    public void Configure(EntityTypeBuilder<SharedLink> builder)
    {
        builder.ToTable("SharedLinks");
        builder.HasKey(x => x.Id);
        // The link id is generated by the application (see SharedLink.Factory), never by the database.
        builder.Property(x => x.Id).ValueGeneratedNever();
        builder.Property(x => x.SharedBy).IsRequired();
        builder.Property(x => x.VideoId).IsRequired();

        builder.HasOne(x => x.Video)
            .WithMany()
            .HasForeignKey(x => x.VideoId)
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        builder.HasIndex(x => x.VideoId);
        builder.HasIndex(x => x.SharedBy);
    }
}
