using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TB.DanceDance.SharedKernel;
using TB.DanceDance.Videos.Domain.Entities;

namespace TB.DanceDance.Videos.Infrastructure.EntitiesConfigurations;

public class SharedLinkConfiguration : IEntityTypeConfiguration<SharedLink>
{
    public void Configure(EntityTypeBuilder<SharedLink> builder)
    {
        builder.ToTable("SharedLinks", Constants.DbSchemas.Video);
        builder.HasKey(x => x.Id);
        // The link id is generated by the application (see SharedLink.Factory), never by the database.
        builder.Property(x => x.Id).ValueGeneratedNever();
        builder.Property(x => x.SharedBy).IsRequired();
        builder.Property(x => x.VideoId).IsRequired();

        builder.HasOne(x => x.Video)
            .WithMany()
            .HasForeignKey(x => x.VideoId)
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        builder.HasIndex(x => x.VideoId);
        builder.HasIndex(x => x.SharedBy);
    }
}
