//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface MyVideosResponse {
    videoInformation?: VideoInformation[];
}

export interface VideoInformation {
    videoId?: string;
    blobId?: string;
    name?: string;
    recordedDateTime?: Date;
    duration?: string | undefined;
    converted?: boolean;
    commentVisibility?: number;
}

export interface UploadUrlResponse {
    sas?: string;
    videoId?: string;
    expireAt?: Date;
}

export interface ProduceUploadUrlResponse extends UploadUrlResponse {
}

export interface ProduceUploadUrlRequest {
    nameOfVideo: string;
    fileName: string;
    recordedTimeUtc: Date;
    sharedWith?: string | undefined;
    sharingWithType: SharingWithType;
    videoId?: string | undefined;
}

export enum SharingWithType {
    NotSpecified = 0,
    Group = 1,
    Event = 2,
    Private = 3,
}

export interface RefreshUploadUrlResponse extends UploadUrlResponse {
}

export interface RefreshUploadUrlRequest {
}

export interface RenameVideoRequest {
    newName?: string;
}

export interface StreamVideoRequest {
}

export interface UpdateCommentSettingsRequest {
    commentVisibility: number;
}

export interface VideoInformationResponse {
    videoInformation?: VideoInformation;
}

export interface VideoInformationRequest {
}

export interface GetPublishSasResponse {
    sas?: string;
}

export interface GetPublishSasRequest {
}

export interface PublicConvertedVideoResponse {
    videoId?: string;
}

export interface PublicConvertedVideoRequest {
}

export interface UpdateVideoInfoRequest {
    videoId: string;
    recordedDateTime: Date;
    duration: string;
    metadata: string;
}

export interface VideoToTransformResponse {
    id?: string;
    fileName?: string;
    sas?: string;
}

export interface SharedLinkResponse {
    linkId?: string;
    videoId?: string;
    videoName?: string;
    createdAt?: Date;
    expireAt?: Date;
    isRevoked?: boolean;
    shareUrl?: string;
    allowComments?: boolean;
    allowAnonymousComments?: boolean;
}

export interface CreateSharedLinkRequest {
    expirationDays?: number;
    allowComments?: boolean;
    allowAnonymousComments?: boolean;
}

export interface ListMySharedLinksResponse {
    links?: SharedLinkResponse[];
}

export interface SharedVideoInfoResponse {
    videoId?: string;
    name?: string;
    duration?: string | undefined;
    recordedDateTime?: Date;
    commentVisibility?: number;
    allowCommentsOnThisLink?: boolean;
    allowAnonymousCommentsOnThisLink?: boolean;
}

export interface VideoInfoBySharedLinkRequest {
}

export interface RevokeSharedLinkRequest {
}

export interface StreamVideoBySharedLinkRequest {
}

export interface ListGroupVideosResponse {
    videos?: VideoFromGroupInformation[];
}

export interface VideoFromGroupInformation extends VideoInformation {
    groupId?: string;
    groupName?: string;
}

export interface ListGroupVideosRequest {
}

export interface CreateNewEventResponse {
    id?: string;
}

export interface CreateNewEventRequest {
    event: EventModel;
}

export interface EventModel {
    id?: string;
    name: string;
    date: Date;
}

export interface ListEventVideosResponse {
    videos?: VideoInformation[];
}

export interface ListEventVideosRequest {
}

export interface CommentResponse {
    id?: string;
    videoId?: string;
    authorName?: string | undefined;
    postedAsAnonymous?: boolean;
    content?: string;
    createdAt?: Date;
    updatedAt?: Date | undefined;
    isHidden?: boolean | undefined;
    isReported?: boolean | undefined;
    reportedReason?: string | undefined;
    isOwn?: boolean;
    canModerate?: boolean;
}

export interface CreateCommentRequest {
    content?: string;
    anonymousId?: string | undefined;
    authorName?: string | undefined;
}

export interface DeleteCommentRequest {
    anonymousId?: string | undefined;
}

export interface HideCommentRequest {
}

export interface ListCommentsByLinkResponse {
    comments?: CommentResponse[];
}

export interface ListCommentsByLink {
}

export interface ListCommentsForVideoResponse {
    comments?: CommentResponse[];
}

export interface ListCommentsForVideoRequest {
}

export interface ReportCommentRequest {
    reason?: string;
}

export interface UnhideCommentRequest {
}

export interface UpdateCommentRequest {
    content?: string;
    anonymousId?: string | undefined;
    authorName?: string | undefined;
}

export interface ApproveAccessRequestRequest {
    requestId?: string;
    isGroup?: boolean;
    isApproved?: boolean;
}

export interface ListAccessRequestsResponse {
    accessRequests?: RequestedAccessModel[];
}

export interface RequestedAccessModel {
    name?: string;
    requestorFirstName?: string;
    requestorLastName?: string;
    whenJoined?: Date | undefined;
    requestId?: string;
    isGroup?: boolean;
}

export interface ListAllEventsAndGroupsResponse {
    events?: EventModel2[];
    groups?: GroupModel[];
}

export interface EventModel2 {
    id?: string;
    name: string;
    date: Date;
}

export interface GroupModel {
    id?: string;
    name?: string;
    seasonStart?: Date;
    seasonEnd?: Date;
}

export interface GetUserAccessResponse {
    assigned?: GetUserAccessSet;
    available?: GetUserAccessSet;
    pending?: ListUserAccessPending;
}

export interface GetUserAccessSet {
    events?: EventModel2[];
    groups?: GroupModel[];
}

export interface ListUserAccessPending {
    events?: string[];
    groups?: string[];
}

export interface RequestAccessRequest {
    events?: string[] | undefined;
    groups?: RequestAccessGroupModel[] | undefined;
}

export interface RequestAccessGroupModel {
    id?: string;
    joinedDate?: Date;
}